backend:
  name: git-gateway
  branch: main # or master, depending on your repo

media_folder: "images/uploads" # where uploaded images will go
public_folder: "/images/uploads"

collections:
  - name: "items"
    label: "Items"
    folder: "content/items"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
